run:
  timeout: 3m
  allow-parallel-runners: true
  go: '1.21'
linters:
  enable:
    # defaults:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # added:
    - bodyclose
    - contextcheck
    - dupl
    - errname
    - exportloopref
    - gocheckcompilerdirectives
    - gocritic # MAYBE NOT THIS ONE
    - godot
    - goimports
    - goprintffuncname
    - gosec
    - importas
    - misspell
    - noctx
    - prealloc
    - revive
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    # currently broken:
    # - musttag

linters-settings:
  govet:
    disable:
      - loopclosure # we use GOEXPERIMENT := "loopvar"
  goimports:
    local-prefixes: github.com/drshriveer/gtools
# if the stutter check in revive is annoying uncomment the following:
#  revive:
#    rules:
#      - name: exported
#        arguments:
#          - disableStutteringCheck
issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments