run:
  skip-files:
    - ".*/libexec/src/slices/sort.go$" # somehow slices (an internal library) fails.
  allow-parallel-runners: true
  go: '1.21'
linters:
  enable:
    # defauls:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # added:
    - bodyclose
    - contextcheck
    - dupl
    - errname
    - exportloopref
    - gocheckcompilerdirectives
    - gocritic # MAYBE NOT THIS ONE
    - godot
    - goimports
    - goprintffuncname
    - gosec
    - importas
    - misspell
    - musttag
    - noctx
    - prealloc
    - revive
    - tparallel
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  goimports:
    local-prefixes: github.com/drshriveer/gtools
# if the stutter check in revive is annoying uncomment the following:
#  revive:
#    rules:
#      - name: exported
#        arguments:
#          - disableStutteringCheck
issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments