name: "Detect Changes"
description: "looks for changes against main so that workflows can be initiated"
outputs:
  go:
    value: ${{ steps.changes.outputs.go }}
runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          go:
            - '.github/**'
            - '**/*.go'
            - '**/go.mod'
            - 'go.work'