name: PostMergeReleaser
run-name: Post Merge → ${{ github.event.pull_request.tile }} by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.work
      - run: just lint

  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.work
      - run: just test

  release:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.work
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}