name: Validation
run-name: validating → ${{ github.event.pull_request.tile }} by @${{ github.actor }}
on: pull_request

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changes:
              - '**/*.go'
              - '**/go.mod'
              - 'go.work'

  lint:
    needs: changes
    if: ${{ needs.changes.outputs.changes == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.work
      - run: just lint

  test:
    needs: changes
    if: ${{ needs.changes.outputs.changes == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.work
      - run: just test
